spring.application.name=shortenurl
app.base-url=http://localhost:8080
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/ShortenURL
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.open-in-view=false


//JWT_Configs

app.jwt.secret=8f42a731b9de4c1e9a0d6f3e8b5c2a7d4e1f9b6c3a8d5e2f7b4c1a6d9e3f0b2
app.jwt.expiry=86400000